package de.mohadipe.ui.test.robot.aufgabe;

public enum AufgabeDaten {
	REIHENFOLGE, KOORDINATE, ROBOT, GRAFIKPFAD, PROTOKOLL, LOGGER, NAME, ZU_DURCHSUCHENDE_GRAFIK, ANZAHL_WIEDERHOLUNGEN, TIMEOUT, SPIEL_LADEN_TIMEOUT, ABWEICHUNG_Y;
}
